export function GET({ site }: { site?: URL }) {
  const origin = (site ?? new URL("https://qazaqlens.org")).origin;
  const body = [
    "User-agent: *",
    "Allow: /",
    "Disallow: /moderate-corrections",
    "Disallow: /profile",
    "Disallow: /api/",
    "",
    "# AI answer engines — explicitly allowed",
    "User-agent: GPTBot",
    "Allow: /",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "",
    "User-agent: anthropic-ai",
    "Allow: /",
    "",
    "User-agent: PerplexityBot",
    "Allow: /",
    "",
    "User-agent: Googlebot",
    "Allow: /",
    "",
    "User-agent: CCBot",
    "Allow: /",
    "",
    "User-agent: cohere-ai",
    "Allow: /",
    "",
    "User-agent: meta-externalagent",
    "Allow: /",
    "",
    "User-agent: Applebot",
    "Allow: /",
    "",
    "User-agent: OAI-SearchBot",
    "Allow: /",
    "",
    "User-agent: PetalBot",
    "Allow: /",
    "",
    `Sitemap: ${origin}/sitemap-index.xml`,
    "",
    "# Machine-readable data",
    `# ${origin}/llms.txt`,
    `# ${origin}/data/export.json`,
  ].join("\n");
  return new Response(body, {
    headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "public, max-age=3600" },
  });
}
